# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cashscript_issuers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cashscript_issuers.proto',
  package='electroncashslp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x63\x61shscript_issuers.proto\x12\x0f\x65lectroncashslp\"V\n\x14IssuerTemplateParams\x12\x15\n\rtemplate_name\x18\x01 \x01(\t\x12\x17\n\x0f\x61rtifact_sha256\x18\x02 \x01(\x0c\x12\x0e\n\x06params\x18\x03 \x03(\x0c\x62\x06proto3'
)




_ISSUERTEMPLATEPARAMS = _descriptor.Descriptor(
  name='IssuerTemplateParams',
  full_name='electroncashslp.IssuerTemplateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_name', full_name='electroncashslp.IssuerTemplateParams.template_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='artifact_sha256', full_name='electroncashslp.IssuerTemplateParams.artifact_sha256', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='electroncashslp.IssuerTemplateParams.params', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['IssuerTemplateParams'] = _ISSUERTEMPLATEPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IssuerTemplateParams = _reflection.GeneratedProtocolMessageType('IssuerTemplateParams', (_message.Message,), {
  'DESCRIPTOR' : _ISSUERTEMPLATEPARAMS,
  '__module__' : 'cashscript_issuers_pb2'
  # @@protoc_insertion_point(class_scope:electroncashslp.IssuerTemplateParams)
  })
_sym_db.RegisterMessage(IssuerTemplateParams)


# @@protoc_insertion_point(module_scope)
