# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cashscript.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cashscript.proto',
  package='electroncashslp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61shscript.proto\x12\x0f\x65lectroncashslp\")\n\nNamedParam\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"X\n\x10ScriptPinPayload\x12\x17\n\x0f\x61rtifact_sha256\x18\x01 \x01(\x0c\x12+\n\x06params\x18\x02 \x03(\x0b\x32\x1b.electroncashslp.NamedParam\"\x8f\x01\n\x14IssuerTemplateParams\x12\x1b\n\x13issuer_defined_name\x18\x01 \x01(\t\x12\x17\n\x0f\x61rtifact_sha256\x18\x02 \x01(\x0c\x12+\n\x06params\x18\x03 \x03(\x0b\x32\x1b.electroncashslp.NamedParam\x12\x14\n\x0cslp_token_id\x18\x04 \x01(\x0c\x62\x06proto3'
)




_NAMEDPARAM = _descriptor.Descriptor(
  name='NamedParam',
  full_name='electroncashslp.NamedParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='electroncashslp.NamedParam.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='electroncashslp.NamedParam.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=78,
)


_SCRIPTPINPAYLOAD = _descriptor.Descriptor(
  name='ScriptPinPayload',
  full_name='electroncashslp.ScriptPinPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='artifact_sha256', full_name='electroncashslp.ScriptPinPayload.artifact_sha256', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='electroncashslp.ScriptPinPayload.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=168,
)


_ISSUERTEMPLATEPARAMS = _descriptor.Descriptor(
  name='IssuerTemplateParams',
  full_name='electroncashslp.IssuerTemplateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuer_defined_name', full_name='electroncashslp.IssuerTemplateParams.issuer_defined_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='artifact_sha256', full_name='electroncashslp.IssuerTemplateParams.artifact_sha256', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='electroncashslp.IssuerTemplateParams.params', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slp_token_id', full_name='electroncashslp.IssuerTemplateParams.slp_token_id', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=314,
)

_SCRIPTPINPAYLOAD.fields_by_name['params'].message_type = _NAMEDPARAM
_ISSUERTEMPLATEPARAMS.fields_by_name['params'].message_type = _NAMEDPARAM
DESCRIPTOR.message_types_by_name['NamedParam'] = _NAMEDPARAM
DESCRIPTOR.message_types_by_name['ScriptPinPayload'] = _SCRIPTPINPAYLOAD
DESCRIPTOR.message_types_by_name['IssuerTemplateParams'] = _ISSUERTEMPLATEPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NamedParam = _reflection.GeneratedProtocolMessageType('NamedParam', (_message.Message,), {
  'DESCRIPTOR' : _NAMEDPARAM,
  '__module__' : 'cashscript_pb2'
  # @@protoc_insertion_point(class_scope:electroncashslp.NamedParam)
  })
_sym_db.RegisterMessage(NamedParam)

ScriptPinPayload = _reflection.GeneratedProtocolMessageType('ScriptPinPayload', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTPINPAYLOAD,
  '__module__' : 'cashscript_pb2'
  # @@protoc_insertion_point(class_scope:electroncashslp.ScriptPinPayload)
  })
_sym_db.RegisterMessage(ScriptPinPayload)

IssuerTemplateParams = _reflection.GeneratedProtocolMessageType('IssuerTemplateParams', (_message.Message,), {
  'DESCRIPTOR' : _ISSUERTEMPLATEPARAMS,
  '__module__' : 'cashscript_pb2'
  # @@protoc_insertion_point(class_scope:electroncashslp.IssuerTemplateParams)
  })
_sym_db.RegisterMessage(IssuerTemplateParams)


# @@protoc_insertion_point(module_scope)
